### ISSUE TITLE
Ui::grid_under_cursor(): called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by tomokao** [tim-harding/neophyte#13]
Neophyte panics on startup:

```
thread 'main' panicked at <snip>/neophyte-0.2.3/src/ui/mod.rs:447:50:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

That's [this line](https://github.com/tim-harding/neophyte/blob/main/src/ui/mod.rs#L452) on main branch. Seems like just replacing the unwrap with `?` makes it work, but there's probably a bigger underlying issue.

I'm on Arch Linux, i3wm using picom. My nvim config is based on [LazyVim](https://www.lazyvim.org/).

**Comment by tim-harding** [comment]
Could you run with `RUST_BACKTRACE=1 RUST_LOG=info`? I tried running with the stock LazyVim starter and was not able to reproduce. You are right of course that there is a deeper issue here, most likely a mistake in updating `draw_order`.

**Comment by tomokao** [comment]
Here:

```
INFO [winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
INFO [neophyte::neovim] Calling method nvim_ui_attach
INFO [neophyte::neovim::stdout_thread] RPC response to 0: Nil
INFO [wgpu_hal::vulkan::instance] Instance version: 0x403112
INFO [wgpu_hal::vulkan::instance] Debug utils not enabled: debug_utils_user_data not passed to Instance::from_raw
INFO [wgpu_hal::vulkan::instance] Enabling device properties2
INFO [wgpu_core::instance] Adapter Vulkan AdapterInfo { name: "NVIDIA GeForce GTX 1660 Ti", vendor: 4318, device: 8578, device_type: DiscreteGpu, driver: "NVIDIA", driver_info: "545.29.06", backend: Vulkan }
INFO [wgpu_core::device::global] configuring surface with SurfaceConfiguration { usage: TextureUsages(RENDER_ATTACHMENT), format: Bgra8UnormSrgb, width: 843, height: 1024, present_mode: AutoVsync, alpha_mode: Opaque, view_formats: [] }
INFO [wgpu_core::device::global] Automatically choosing presentation mode by rule AutoVsync. Chose Fifo
INFO [neophyte::event_handler] New Winit events
INFO [neophyte::event_handler] Got resize: PhysicalSize { width: 843, height: 1024 }
INFO [neophyte::neovim] Calling method nvim_ui_try_resize_grid
INFO [wgpu_core::device::global] configuring surface with SurfaceConfiguration { usage: TextureUsages(RENDER_ATTACHMENT), format: Bgra8UnormSrgb, width: 843, height: 1024, present_mode: AutoVsync, alpha_mode: Opaque, view_formats: [] }
INFO [wgpu_core::device::global] Automatically choosing presentation mode by rule AutoVsync. Chose Fifo
INFO [neophyte::event_handler] Got cursor move: PhysicalPosition { x: 159.0, y: 385.0 }
thread 'main' panicked at <snip>/neophyte-0.2.3/src/ui/mod.rs:447:50:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: neophyte::ui::Ui::grid_under_cursor
   5: neophyte::event_handler::EventHandler::cursor_moved
   6: neophyte::event_handler::EventHandler::handle
   7: winit::platform_impl::platform::x11::EventLoop<T>::drain_events::{{closure}}
   8: winit::platform_impl::platform::x11::event_processor::EventProcessor<T>::process_event
   9: winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand
  10: neophyte::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
INFO [neophyte::neovim::stdin_thread] receiving on a closed channel
INFO [neophyte::neovim::stdin_thread] Closing stdin thread
INFO [wgpu_core::global] Dropping Global
INFO [neophyte::neovim::stdout_thread] Got Neovim EOF
INFO [wgpu_core::device] Destroying 0 command encoders
```

Also, I realize now it happens independent of the nvim config, if I rename `~/.config/nvim` to something else the same error happens

**Comment by tim-harding** [comment]
I previously had grid `1` initialized in `Ui::new`, which I think caused this issue because Neovim usually sets us up before any window events. It seems that is not the case on your system. I made a few changes to make initialization more robust. Would you try again with the latest revision?

**Comment by tomokao** [comment]
Yes, I tested with latest main and it works now
